global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # uncomment this to scrape prometheus itself
  # - job_name: "prometheus"
  #   static_configs:
  #     - targets: ["localhost:9090"]
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]
