[book]
title = "Berkeleytime Documentation"
authors = ["Berkeleytime Developers"]
description = "The Berkeleytime documentation for developers"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/asuc-octo/berkeleytime/tree/main/docs"
edit-url-template = "https://github.com/asuc-octo/berkeleytime/tree/main/docs/{path}"

[preprocessor.alerts]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
