apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rook-cephrbd
  namespace: rook-ceph
spec:
  replicated:
    requireSafeReplicaSize: false
    size: 1

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-cephrbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-ceph
  pool: rook-cephrbd
  imageFormat: "2"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
reclaimPolicy: Delete
mountOptions:
  - discard
# ---
# apiVersion: snapshot.storage.k8s.io/v1beta1
# kind: VolumeSnapshotClass
# metadata:
#   name: csi-rbdplugin-snapclass
# driver: rook-ceph.rbd.csi.ceph.com
# parameters:
#   clusterID: rook-ceph
#   csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
#   csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
# deletionPolicy: Delete
