apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "bt-app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "0" # reset hsts to allow access to old.berkeleytime.com
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: bt-cert
  rules:
    # main host rule
    - host: {{ .Values.host }}
      http:
        paths:
          - path: {{ .Values.frontend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "bt-app.frontendName" . }}-svc
                port:
                  number: {{ .Values.port }}
          - path: {{ .Values.backend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "bt-app.backendName" . }}-svc
                port:
                  number: {{ .Values.port }}
          - path: /go
            pathType: Prefix
            backend:
              service:
                name: {{ include "bt-app.backendName" . }}-svc
                port:
                  number: {{ .Values.port }}
          - path: /banner
            pathType: Prefix
            backend:
              service:
                name: {{ include "bt-app.backendName" . }}-svc
                port:
                  number: {{ .Values.port }}
