{{- if .Files.Glob "migrations/*.js" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-migrations
  labels:
    {{- include "bt-mongo.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "migrations/*.js" }}
  {{ base $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
{{- end }}
